### ISSUE TITLE
Comparison with climb?

### ISSUE THREAD

**Issue by webflo** [nella/victor#3]
Hi, great idea. This tools looks very similar to climb (https://github.com/vinkla/climb). Can you explain the difference?

Thanks!

**Comment by Vrtak-CZ** [comment]
HI, I don't know climb before you post this issue. Before I'm started working on Victor I was trying googling something similar but found nothing.

Main difference with climb is **private repositories support (satis)**. Because Victor internally use composer.

Second difference is **respecting your dependency preferences**. I you have `"nella/victor": "~1.0.0"` in your composer Victor check only `1.0.x` versions. So you are currently have 1.0.0, but there is a 1.0.1 and 2.0.0, Victror shows you 1.0.1 as latest version because of `~1.0.0`.

There are also options `--ignore-required-version|-f` for disabling dependency preferences and `--exact-as-tilda|-t` replace your "hard" dependency `"nella/victor": "1.0.0"` with "tilda" dependency `"nella/victor": "~1.0.0"`.
